from .kernels import (
    # trend change
    accel,
    # tenure / activity
    active_months,
    active_run_count,
    activity_rate,
    # new groups
    acf_characteristic_scale,
    agg_autocorrelation,
    # smoothness
    alternation_rate,
    # autocorr & seasonal
    autocorr,
    auto_period,
    automutual_info,
    # new groups
    burstiness,
    c3,
    change_quantiles,
    client_age,
    # structural signals
    corr_with_time,
    cross_window_momentum,
    # relative position
    cumulative_share,
    cusum,
    # new groups
    dfa,
    # trend
    direction_flag,
    distance_to_global_max,
    energy_ratio_by_chunks,
    entropy,
    # dynamics ratios
    ewma,
    extreme_events,
    # volatility
    extreme_share,
    flow_regularity,
    # log growth
    geometric_return,
    gini,
    growth_quality,
    growth_since_start,
    half_ratio,
    inactive_streak,
    index_mass_quantile,
    # distribution moments
    kurtosis_proxy,
    lag1_diff,
    lag_comparison,
    lag_growth_ratio,
    level_ratio,
    lifecycle_phase,
    local_extrema,
    log1p_level,
    log_level,
    log_slope,
    log_slope_ratio,
    log_volatility,
    longest_active_run,
    max_abs_jump,
    max_drawdown,
    mean_deviation_shape,
    mean_median_gap,
    microstructure,
    momentum,
    nonlinearity,
    pct_of_max,
    peak_trough_timing,
    permutation_entropy,
    plateau,
    quantile_persistence,
    rank_in_window,
    recency,
    recent_share,
    recovery_dynamics,
    regime_change,
    rolling_cv,
    rolling_min_max,
    rolling_std,
    rolling_sum,
    roughness_ratio,
    run_above_mean,
    seasonal_autocorr,
    segment_gap,
    sign_change_count,
    skew_proxy,
    slope,
    slope_ratio,
    streak,
    tenure,
    time_weighted_momentum,
    total_variation,
    transition_matrix,
    trend_consistency,
    trend_flip,
    trough_to_current,
    value_clustering,
    volatility_of_diff,
    volatility_trend,
    # simple statistics
    window_mean,
    window_median,
    window_volatility_ratios,
    zero_clustering,
    zero_share,
    zscore,
)

TRANSFORMERS: dict = {
    m.FEATURE: m
    for m in [
        # simple statistics
        window_mean,
        window_median,
        # trend
        direction_flag,
        growth_since_start,
        momentum,
        slope,
        slope_ratio,
        streak,
        # volatility
        extreme_share,
        rolling_cv,
        rolling_min_max,
        rolling_std,
        skew_proxy,
        # tenure / activity
        active_months,
        active_run_count,
        activity_rate,
        client_age,
        inactive_streak,
        longest_active_run,
        recency,
        tenure,
        zero_share,
        # dynamics ratios
        ewma,
        lag1_diff,
        mean_median_gap,
        recent_share,
        rolling_sum,
        zscore,
        # trend change
        accel,
        max_abs_jump,
        max_drawdown,
        peak_trough_timing,
        run_above_mean,
        sign_change_count,
        time_weighted_momentum,
        trend_flip,
        volatility_of_diff,
        # relative position
        cumulative_share,
        distance_to_global_max,
        half_ratio,
        lag_growth_ratio,
        level_ratio,
        local_extrema,
        log1p_level,
        pct_of_max,
        rank_in_window,
        trough_to_current,
        volatility_trend,
        # structural signals
        corr_with_time,
        cusum,
        entropy,
        gini,
        # autocorr & seasonal
        autocorr,
        seasonal_autocorr,
        # segmentation
        segment_gap,
        # log growth
        geometric_return,
        log_level,
        log_slope,
        log_slope_ratio,
        log_volatility,
        # smoothness
        alternation_rate,
        roughness_ratio,
        total_variation,
        # distribution moments
        kurtosis_proxy,
        # new groups
        burstiness,
        cross_window_momentum,
        extreme_events,
        flow_regularity,
        growth_quality,
        lag_comparison,
        lifecycle_phase,
        mean_deviation_shape,
        microstructure,
        nonlinearity,
        plateau,
        quantile_persistence,
        recovery_dynamics,
        regime_change,
        trend_consistency,
        value_clustering,
        window_volatility_ratios,
        zero_clustering,
        # nonlinearity / complexity / spectral-adjacent (tsfresh-inspired)
        c3,
        permutation_entropy,
        change_quantiles,
        energy_ratio_by_chunks,
        index_mass_quantile,
        agg_autocorrelation,
        # fractal / regime / memory-scale / spectral-adjacent (catch22 & tsfel-inspired)
        dfa,
        transition_matrix,
        acf_characteristic_scale,
        automutual_info,
        auto_period,
    ]
}

AVAILABLE_TRANSFORMERS = list(TRANSFORMERS)
