from .kernels import (
    # simple statistics
    window_mean,
    window_median,
    # trend
    direction_flag,
    growth_since_start,
    momentum,
    slope,
    slope_ratio,
    streak,
    # volatility
    extreme_share,
    rolling_cv,
    rolling_min_max,
    rolling_std,
    skew_proxy,
    # tenure / activity
    active_months,
    active_run_count,
    activity_rate,
    client_age,
    inactive_streak,
    longest_active_run,
    recency,
    tenure,
    zero_share,
    # dynamics ratios
    ewma,
    lag1_diff,
    mean_median_gap,
    recent_share,
    rolling_sum,
    zscore,
    # trend change
    accel,
    max_abs_jump,
    max_drawdown,
    peak_trough_timing,
    run_above_mean,
    sign_change_count,
    time_weighted_momentum,
    trend_flip,
    volatility_of_diff,
    # relative position
    cumulative_share,
    distance_to_global_max,
    half_ratio,
    lag_growth_ratio,
    level_ratio,
    local_extrema,
    log1p_level,
    pct_of_max,
    rank_in_window,
    trough_to_current,
    volatility_trend,
    # structural signals
    corr_with_time,
    cusum,
    entropy,
    gini,
    # autocorr & seasonal
    autocorr,
    seasonal_autocorr,
    # log growth
    geometric_return,
    log_level,
    log_slope,
    log_slope_ratio,
    log_volatility,
    # smoothness
    alternation_rate,
    roughness_ratio,
    total_variation,
    # distribution moments
    kurtosis_proxy,
    # new groups
    burstiness,
    cross_window_momentum,
    extreme_events,
    flow_regularity,
    growth_quality,
    lag_comparison,
    lifecycle_phase,
    mean_deviation_shape,
    microstructure,
    nonlinearity,
    plateau,
    quantile_persistence,
    recovery_dynamics,
    regime_change,
    trend_consistency,
    value_clustering,
    window_volatility_ratios,
    zero_clustering,
)

TRANSFORMERS: dict = {
    m.FEATURE: m
    for m in [
        # simple statistics
        window_mean,
        window_median,
        # trend
        direction_flag,
        growth_since_start,
        momentum,
        slope,
        slope_ratio,
        streak,
        # volatility
        extreme_share,
        rolling_cv,
        rolling_min_max,
        rolling_std,
        skew_proxy,
        # tenure / activity
        active_months,
        active_run_count,
        activity_rate,
        client_age,
        inactive_streak,
        longest_active_run,
        recency,
        tenure,
        zero_share,
        # dynamics ratios
        ewma,
        lag1_diff,
        mean_median_gap,
        recent_share,
        rolling_sum,
        zscore,
        # trend change
        accel,
        max_abs_jump,
        max_drawdown,
        peak_trough_timing,
        run_above_mean,
        sign_change_count,
        time_weighted_momentum,
        trend_flip,
        volatility_of_diff,
        # relative position
        cumulative_share,
        distance_to_global_max,
        half_ratio,
        lag_growth_ratio,
        level_ratio,
        local_extrema,
        log1p_level,
        pct_of_max,
        rank_in_window,
        trough_to_current,
        volatility_trend,
        # structural signals
        corr_with_time,
        cusum,
        entropy,
        gini,
        # autocorr & seasonal
        autocorr,
        seasonal_autocorr,
        # log growth
        geometric_return,
        log_level,
        log_slope,
        log_slope_ratio,
        log_volatility,
        # smoothness
        alternation_rate,
        roughness_ratio,
        total_variation,
        # distribution moments
        kurtosis_proxy,
        # new groups
        burstiness,
        cross_window_momentum,
        extreme_events,
        flow_regularity,
        growth_quality,
        lag_comparison,
        lifecycle_phase,
        mean_deviation_shape,
        microstructure,
        nonlinearity,
        plateau,
        quantile_persistence,
        recovery_dynamics,
        regime_change,
        trend_consistency,
        value_clustering,
        window_volatility_ratios,
        zero_clustering,
    ]
}

AVAILABLE_TRANSFORMERS = list(TRANSFORMERS)
